// Copyright 2024 Henri Rebecq
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Trictrac — C++ OpenSpiel game backed by the Rust engine (cxxengine.rs).
//
// Game name: "trictrac"
// Parameters:
//   "max_turns" int  Maximum player turns before forced termination (default 1000)

#ifndef OPEN_SPIEL_GAMES_TRICTRAC_H_
#define OPEN_SPIEL_GAMES_TRICTRAC_H_

#include <memory>
#include <string>
#include <vector>

#include "open_spiel/spiel.h"
#include "open_spiel/spiel_utils.h"

// Generated by corrosion_add_cxxbridge from trictrac/store/src/cxxengine.rs.
// The include path is provided by the trictrac_cxx_bridge CMake target's
// INTERFACE_INCLUDE_DIRECTORIES.
#include "trictrac_cxx_bridge/cxxengine.h"

namespace open_spiel {
namespace trictrac {

// Action-space size: 0=Roll, 1=Go, 2-513=Move (matches ACTION_SPACE_SIZE in Rust).
inline constexpr int kNumDistinctActions = 514;
// 6×6 dice outcomes, all equally probable.
inline constexpr int kNumChanceOutcomes = 36;
// State vector length (matches GameState::to_vec() in Rust).
inline constexpr int kStateEncodingSize = 36;
inline constexpr int kDefaultMaxTurns = 1000;

class TrictracGame;

// ---------------------------------------------------------------------------

class TrictracState : public State {
 public:
  explicit TrictracState(std::shared_ptr<const Game> game);
  // Copy constructor performs a deep-copy of the Rust engine via clone_engine().
  TrictracState(const TrictracState& other);

  Player CurrentPlayer() const override;
  std::vector<Action> LegalActions() const override;
  std::string ActionToString(Player player, Action move_id) const override;
  std::vector<std::pair<Action, double>> ChanceOutcomes() const override;
  std::string ToString() const override;
  bool IsTerminal() const override;
  std::vector<double> Returns() const override;
  std::string ObservationString(Player player) const override;
  void ObservationTensor(Player player, absl::Span<float> values) const override;
  std::unique_ptr<State> Clone() const override;

 protected:
  void DoApplyAction(Action move_id) override;

 private:
  // Decode a chance-node action index [0,35] to (die1, die2).
  // Matches Python: [(i,j) for i in range(1,7) for j in range(1,7)][action]
  static trictrac_engine::DicePair DecodeChanceAction(Action action);

  rust::Box<trictrac_engine::TricTracEngine> engine_;
};

// ---------------------------------------------------------------------------

class TrictracGame : public Game {
 public:
  explicit TrictracGame(const GameParameters& params);

  int NumDistinctActions() const override { return kNumDistinctActions; }
  std::unique_ptr<State> NewInitialState() const override;
  int MaxChanceOutcomes() const override { return kNumChanceOutcomes; }
  int NumPlayers() const override { return 2; }
  double MinUtility() const override { return 0.0; }
  double MaxUtility() const override { return 200.0; }
  // Rough upper bound: chance node + roll action + move per turn, times max turns.
  int MaxGameLength() const override { return 3 * max_turns_; }
  int MaxChanceNodesInHistory() const override { return MaxGameLength(); }
  std::vector<int> ObservationTensorShape() const override {
    return {kStateEncodingSize};
  }

 private:
  int max_turns_;
};

}  // namespace trictrac
}  // namespace open_spiel

#endif  // OPEN_SPIEL_GAMES_TRICTRAC_H_
